In [121]:
import pandas as pd 
import numpy as np

In [122]:
df = pd.read_csv("C:\\Users\\asimg\\emp_rates.csv")

In [123]:
df.head()

,year,month,day,statefips,emp_combined,emp_combined_inclow,emp_combined_incmiddle,emp_combined_inchigh,emp_combined_ss40,emp_combined_ss60,emp_combined_ss65,emp_combined_ss70
0,2020,1,14,1,-0.00403,-0.000697,-0.00875,.00141,.00197,0.00259,-.00564,-.00747
1,2020,1,14,2,-0.00309,0.028900,-0.00137,-.023,.0138,0.04100,-.0451,.0227
2,2020,1,14,4,-0.00411,-0.000020,-0.00674,-.00237,-.000175,0.00170,-.00486,-.00678
3,2020,1,14,5,-0.00502,-0.007070,-0.00742,.,.00359,-0.00932,.,-.0225
4,2020,1,14,6,-0.00590,0.005770,-0.00849,-.00547,-.002,-0.00489,-.00798,-.00678

In [124]:
df_filter = df[df["statefips"] == 17]

In [125]:
df_filter= df_filter.replace('.','0')

In [126]:
df_filter[["emp_combined","emp_combined_inclow", "emp_combined_incmiddle", "emp_combined_inchigh", "emp_combined_inchigh","emp_combined_ss40", "emp_combined_ss60", "emp_combined_ss65", "emp_combined_ss70" ]]= df_filter[["emp_combined","emp_combined_inclow", "emp_combined_incmiddle", "emp_combined_inchigh", "emp_combined_inchigh","emp_combined_ss40", "emp_combined_ss60", "emp_combined_ss65", "emp_combined_ss70"]].apply(pd.to_numeric)

In [127]:
df_filter

,year,month,day,statefips,emp_combined,emp_combined_inclow,emp_combined_incmiddle,emp_combined_inchigh,emp_combined_ss40,emp_combined_ss60,emp_combined_ss65,emp_combined_ss70
13,2020,1,14,17,-0.00414,-0.00449,-0.005350,-0.001970,-0.002860,-0.007480,-0.004550,-0.01080
64,2020,1,15,17,-0.00316,-0.00361,-0.003940,-0.001600,-0.002160,-0.005260,-0.002980,-0.01060
115,2020,1,16,17,-0.00223,-0.00275,-0.002610,-0.001270,-0.001440,-0.003170,-0.001550,-0.01040
166,2020,1,17,17,-0.00134,-0.00188,-0.001380,-0.000932,-0.000640,-0.001250,-0.000254,-0.00994
217,2020,1,18,17,-0.00048,-0.00095,-0.000227,-0.000575,0.000216,0.000489,0.000847,-0.00917
...,...,...,...,...,...,...,...,...,...,...,...,...
12763,2020,9,20,17,-0.04660,-0.25200,0.000680,0.013500,-0.052100,-0.029100,-0.043900,-0.18100
12814,2020,9,21,17,-0.04620,-0.25100,0.001260,0.013600,-0.051300,-0.028800,-0.043400,-0.18100
12865,2020,9,22,17,-0.04580,-0.25100,0.001810,0.013500,-0.050400,-0.028700,-0.043100,-0.18100
12916,2020,9,23,17,-0.04560,-0.25000,0.002260,0.013200,-0.049300,-0.028600,-0.043100,-0.18100
12967,2020,9,24,17,-0.04550,-0.25000,0.002570,0.012600,-0.048000,-0.028700,-0.043500,-0.18000

In [128]:
df_month = df_filter.groupby(["year","month","statefips"], as_index=False).agg({"emp_combined": "mean","emp_combined_inclow" : "mean", "emp_combined_incmiddle" : "mean", "emp_combined_inchigh": "mean", "emp_combined_inchigh": "mean","emp_combined_ss40": "mean", "emp_combined_ss60": "mean", "emp_combined_ss65": "mean", "emp_combined_ss70" : "mean" })

In [130]:
df_final=df_month.rename(columns={"emp_combined": "EmplyRate_Combined","emp_combined_inclow": "EmplyRate_LowIncome", "emp_combined_incmiddle":"EmplyRate_MiddleIncome", "emp_combined_inchigh": "EmplyRate_HighIncome","emp_combined_ss40":"Trade_Transport_Utilites", "emp_combined_ss60":"Professional_Business", "emp_combined_ss65":"Education_Health", "emp_combined_ss70":"Leisure_Hospitality"})

In [131]:
df_final

,year,month,statefips,EmplyRate_Combined,EmplyRate_LowIncome,EmplyRate_MiddleIncome,EmplyRate_HighIncome,Trade_Transport_Utilites,Professional_Business,Education_Health,Leisure_Hospitality
0,2020,1,17,0.002312,0.001971,0.003163,0.001169,0.001809,0.004657,0.003245,0.000993
1,2020,2,17,0.009382,0.007643,0.007779,0.013106,0.001826,0.015172,0.010042,0.028672
2,2020,3,17,-0.020306,-0.048536,-0.019700,-0.002645,-0.013884,-0.005470,-0.008577,-0.089711
3,2020,4,17,-0.165967,-0.299767,-0.165100,-0.078603,-0.124180,-0.110943,-0.140983,-0.515167
4,2020,5,17,-0.140323,-0.287806,-0.143548,-0.037417,-0.108932,-0.083032,-0.133068,-0.443032
5,2020,6,17,-0.090343,-0.220400,-0.088077,-0.007935,-0.070060,-0.043780,-0.087077,-0.327167
6,2020,7,17,-0.066626,-0.215452,-0.039242,-0.012087,-0.058384,-0.034916,-0.070713,-0.224452
7,2020,8,17,-0.054913,-0.247548,-0.007193,-0.003966,-0.058955,-0.032632,-0.054039,-0.179548
8,2020,9,17,-0.049508,-0.258792,-0.000621,0.010587,-0.054804,-0.031812,-0.046387,-0.182208

In [132]:
df_final.to_csv("c:\\users\\asimg\Documents\\EmpRatesFinal1.csv")